import "./globals.css";
import { Cinzel, Merriweather, IM_Fell_English, Lora, Roboto } from "next/font/google";

const cinzel = Cinzel({ 
  subsets: ["latin"],
  variable: '--fontHeading',
});

const merriweather = Merriweather({
    subsets: ["latin"],
    weight: ['300', '400', '700', '900'],
    variable: "--fontQuote",
});

const imFellEnglish = IM_Fell_English({
    subsets: ["latin"],
    weight: ['400'],
    variable: "--fontSubheading",
});

const lora = Lora({
    subsets: ["latin"],
    variable: "--fontTextSerif",
});

const roboto = Roboto({
    subsets: ["latin"],
    weight: ['100', '300', '400', '500', '700', '900'],
    variable: "--fontTextSansSerif",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${cinzel.variable} ${merriweather.variable} ${imFellEnglish.variable} ${lora.variable} ${roboto.variable}`}
        >
            <body>{children}</body>
        </html>
    );
}
